version: 2.1

jobs:
  build: 
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-
      
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
workflows:
  hello-docker: 
    jobs:
      - build